#!/bin/bash

echo "<!DOCTYPE html>"
echo "<html lang='en'>"
echo "<head>"
echo "    <meta charset='UTF-8'>"
echo "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
echo "    <title>System Statistics</title>"
echo "    <style>"
echo "        body {"
echo "            font-family: Arial, sans-serif;"
echo "            margin: 20px;"
echo "            padding: 20px;"
echo "            background-color: #f0f0f0;"
echo "        }"
echo "        .container {"
echo "            max-width: 800px;"
echo "            margin: 0 auto;"
echo "            background-color: #fff;"
echo "            padding: 20px;"
echo "            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);"
echo "        }"
echo "        h1 {"
echo "            text-align: center;"
echo "            color: #333;"
echo "        }"
echo "        pre {"
echo "            background-color: #272822;"
echo "            color: #f8f8f2;"
echo "            padding: 10px;"
echo "            border-radius: 5px;"
echo "            overflow: auto;"
echo "        }"
echo "    </style>"
echo "</head>"
echo "<body>"
echo "    <div class='container'>"
echo "        <h1>System Statistics</h1>"
echo "        <pre>"

# System statistics
echo "CPU Usage:"
top -l 1 | grep "CPU usage" | awk '{print $3 $4 $5 $6 $7 $8 $9 $10 $11 $12 $13 $14}'
echo ""
echo "Memory Usage:"
vm_stat | perl -ne '/page size of (\d+)/ and $size=$1; /Pages free:\s+(\d+)/ and $free=$1; /Pages active:\s+(\d+)/ and $active=$1; /Pages inactive:\s+(\d+)/ and $inactive=$1; /Pages speculative:\s+(\d+)/ and $spec=$1; /Pages wired down:\s+(\d+)/ and $wired=$1; /Pages occupied by compressor:\s+(\d+)/ and $compress=$1; END { $total=($free+$active+$inactive+$spec+$wired+$compress)*$size; $used=($active+$wired+$compress)*$size; printf("%.2f GB / %.2f GB (%.2f%%)\n", $used/1024/1024/1024, $total/1024/1024/1024, $used*100/$total); }'
echo ""
echo "Disk Usage:"
df -h | grep '^/dev/' | awk '{ print $5 " " $1 }'
echo ""
echo "Running Processes:"
ps aux -m | awk 'NR<=10{print $0}'

echo "        </pre>"
echo "    </div>"
echo "</body>"
echo "</html>"
